# Generated by Django 3.2 on 2021-12-05 15:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
            ],
        ),
        migrations.CreateModel(
            name='UserPostScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='score')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_users', to='post.post', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scored_posts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
